### ISSUE TITLE
I cannot read Pole Dipole files

### ISSUE THREAD

**Issue by Khalilsqu** [RJbalikian/InvPyplot#2]
Traceback (most recent call last):
  File "d:\consultancy works squ\sultan_ert_plot\Inversion\test_read.py", line 7, in <module>
    invplot.read_inv_data(inv_file1, inv_dict=inv_dict, instrument="4000")
  File "d:\consultancy works squ\sultan_ert_plot\Inversion\invplot.py", line 582, in read_inv_data
    inDF.columns = inDF_cols
    ^^^^^^^^^^^^
  File "C:\Users\kalho\miniconda3\Lib\site-packages\pandas\core\generic.py", line 6307, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "C:\Users\kalho\miniconda3\Lib\site-packages\pandas\core\generic.py", line 813, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "C:\Users\kalho\miniconda3\Lib\site-packages\pandas\core\internals\managers.py", line 239, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "C:\Users\kalho\miniconda3\Lib\site-packages\pandas\core\internals\base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 11 elements, new values have 4 elements

Pole dipole has only three electrodes,

`inDF_cols=['NoElectrodes', 'A(x)', 'A(z)', 'B(x)', 'B(z)', 'M(x)', 'M(z)', 'N(x)', 'N(z)', 'Data']`

the above code wont work

**Comment by RJbalikian** [comment]
Thanks for posting this. It is having trouble parsing your .inv file. This is an issue with the reading in of the actual data portion of the .inv file. It is because I have not been able to generalize the input function as much as I would like.

Yes, right now it is optimized for dipole dipole since that is what most of my sample files are in.

Do you have a file you can send? I am trying to make it more generic, but I only have a handful of my own files to work from and I'm not sure what all the variations might be. If you send it, I will both update the code and make sure it is working with your file specifically.

Also, what instrument was your .inv data collected with? That might also make a difference.
